### PR TITLE
fix(gateway): JSON when Accept is a list

### LINKED ISSUE #9520: 0.18.0-rc2: 400 when "Accept: application/json, text/plain"
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
docker run -p 8080:8080 --rm ipfs/kubo:v0.18.0-rc1
```

### Config

```json
Default for docker container.
```

### Description

Pinata made my Christmas interesting by making rc0.18 their prod-facing release, so apologies if this RC isn't to the point of stability where you care about this sort of thing, but since I did all the work to track it down, here's the info. :) Best!

```shell
$ docker run -p 8080:8080 --rm ipfs/kubo:v0.18.0-rc1 &
$ http localhost:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa Accept:'application/json'
> [200 OK, ...successful output...]
$ http localhost:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa Accept:'application/json, text/plain'
> HTTP/1.1 400 Bad Request
Content-Length: 87
Content-Type: text/plain; charset=utf-8
Date: Mon, 26 Dec 2022 12:02:19 GMT
Location: http://bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa.ipfs.localhost:8080/
X-Content-Type-Options: nosniff

error while processing the Accept header: mime: unexpected content after media subtype
$ http localhost:8080/ipfs/bafybeieznmzzuxoxqwmkgy5yycefaehgoswvc6yiu6mfhbblzkkj77w7oa Accept:'foo/bar, application/json, text/plain'
> [200 OK, ...successful output...]
```

Suspect this was introduced in https://github.com/ipfs/kubo/commit/fdd19656c465f07ff6d7be653f5438d74a0c0c2f with error on line https://github.com/ipfs/kubo/blob/fdd19656c465f07ff6d7be653f5438d74a0c0c2f/core/corehttp/gateway_handler.go#L898

### PR DESCRIPTION
**Pull request by lidel**
This PR fixes #9520 by adding basic support for `Accept` headers with a list of content types (pick the first matching one).

cc @hacdias if you have time to eyeball – would like to include this in 0.18.

## Context

Block/CAR responses introduced in https://github.com/ipfs/go-ipfs/pull/8758 always had single explicit type, and we did not bother with implementing/testing lists.

With the introduction of JSON  added in https://github.com/ipfs/kubo/pull/9335 (Kubo 0.18) people started passing a list, as noted in #9520.  

Note: this PR does not implement weights because afaik  [golang still does not include this in standard library](https://groups.google.com/g/golang-dev/c/5pOqD2wKpN4/m/G5rfULC2KZ0J), and I wanted to avoid adding dependency like https://github.com/aohorodnyk/mimeheader.  Returning the first match should be good enough for now, as we don't have a use case where the user would like to mix CAR and JSON.

Closes #9520

### CODE REVIEW

**Review by hacdias — APPROVED** [review]

**Comment by hacdias** [comment]
Thanks for this, it makes sense to be fixed.
