### ISSUE TITLE
ipfs add --help is broken

### ISSUE THREAD

**Issue by chriscool** [ipfs/kubo#373]
Right now on master () I get:

```
$ ipfs add --help
Error: Argument 'path' is required

USAGE:

    ipfs add <path>... - Add an object to ipfs.

    Adds contents of <path> to ipfs. Use -r to add directories.
    Note that directories are added recursively, to form the ipfs
    MerkleDAG. A smarter partial add with a staging area (like git)
    remains to be implemented.

Use 'ipfs add --help' for more information about this command.
```

It is not so easy to find where this problem appeared because ipfs2 became ipfs, but I think that the problem comes from the merge of PR #357.

It doesn't work with ipfs2 at:

105f232 (HEAD) Merge pull request #357 from jbenet/multifile

It used to work with ipfs2 at:

1c36d52 Merge pull request #359 from jbenet/feat/swarm-cmd

I tried to bisect between the above two commits but I get too many compilation errors on Linux.
I had to use `git bisect skip` a lot to try to overcome that, but in the end I get:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
5614234d1d77952f9a7e7b71235e3261d199e113
a9d784cb21c8788a1e65e242d83067229a509c82
c598673b4cda659038209a076881556d1c384f96
bfdf7951b39f238e09d49f6d86aecf36d27bf395
c9abc6b546c11d94f3d21a0447ec2d6f70dc3833
380337b76b24751af4b512646939760717a8322c
8900229579ff244c062ceb875aa528f0c3530049
015bd06cffe4003773f3bafaf01f1198055accca
bde015616f30482bb661a3051ba8845cf6a4db0f
0b509098aa39d8d8acdca75e8c08409d22c8ddfe
c904e6c46da68bf9470eb3e1891465f58df77ac0
c14bd98f7a2057977f3a72b140c498637e5a8df5
d4ac442838aec986891b7efc5e6f6f11ae5df407
6681c5037114b99a4c122ef498c51e4be295df7d
ce49541f130e736639ff270ad0132245f2938ee8
57c48adfcff1237deafb2188db69e507dc41097f
9333c504c12b76d1577e478e5e013b37e211ae7f
bc8a97c119393060b242605ec05ec770b68825ba
c19bdf18b2044a254d0fc490c85ce26ca89e1790
8968b98cf356625440e44a24a4154a55795314f1
d1f1d2f5bf2adcc726856de0c681b24ba8fc6651
0709621a2c8436afa90c80e147985cc05723a73e
f8be26810ae1359f10f263b461d8bdba61daf56e
a0bd29d5beb34ea7e23736525a5050525365f0e6
We cannot bisect more!
```
