### ISSUE TITLE
Kubo does not compile with golang 1.27.0

### ISSUE THREAD

**Issue by user-1969** [ipfs/kubo#11438]
### Checklist

- [x] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [x] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [x] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text

```

### Config

```json

```

### Description

Since updating to Go version go1.27.0-X:nodwarf5 linux/amd64, Kubo no longer compiles, with this output:
``$ make build
go: downloading github.com/ipfs/boxo v0.42.3-0.20260827015437-63cae36adc96
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go build "-trimpath" -ldflags="-X "github.com/ipfs/kubo".CurrentCommit=a554311d4 -X "github.com/ipfs/kubo".taggedRelease= -X "github.com/ipfs/kubo".buildOrigin=github.com/ipfs/kubo" -o "cmd/ipfs/ipfs" "github.com/ipfs/kubo/cmd/ipfs"
# github.com/cockroachdb/swiss
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:286:7: undefined: hashFn
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:337:14: undefined: getRuntimeHasher
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:338:22: undefined: fastrand64
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:600:23: undefined: fastrand64
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:649:19: undefined: fastrand64
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:670:20: undefined: fastrand64
../../go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/options.go:30:14: undefined: hashFn
make: *** [cmd/ipfs/Rules.mk:21: cmd/ipfs/ipfs] Error 1
``

**Comment by Expooo7** [comment]
its because go updated to version `1.27.0` and that dependency `cockroachdb` is doing something which embeds itself into go internals.
Try to compile using go version `1.26.4`, that is what I use on arch linux (using `mise` program to get the older version of go). `Cockroachdb` has to fix this on their side afaik

**Comment by lidel** [comment]
Thank you for reporting. This should be fixed by #11451, which bumped `go-ds-pebble` to v0.5.13 and with it `cockroachdb/swiss` to a build that supports Go 1.27. 

The fix will be cherry-picked into v0.43.1, planned before Sep 30. 
Until then, build from master.
